spring:
  application:
    name: kordi-api

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/kordi}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email, profile

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 1800000
  refresh-token-expiry: 1209600000

app:
  oauth2:
    redirect-url: ${OAUTH2_REDIRECT_URL:http://localhost:3000/api/auth/callback}
