-- EASY: Major, Minor, Seventh, Minor Seventh, Dim, Aug
INSERT IGNORE INTO quiz_chords (chordkey, chord_type, name, notes, difficulty) VALUES
-- Major
('C', 'MAJOR', 'C', 'C,E,G', 'EASY'),
('C#', 'MAJOR', 'C#', 'C#,F,G#', 'EASY'),
('D', 'MAJOR', 'D', 'D,F#,A', 'EASY'),
('D#', 'MAJOR', 'D#', 'D#,G,A#', 'EASY'),
('E', 'MAJOR', 'E', 'E,G#,B', 'EASY'),
('F', 'MAJOR', 'F', 'F,A,C', 'EASY'),
('F#', 'MAJOR', 'F#', 'F#,A#,C#', 'EASY'),
('G', 'MAJOR', 'G', 'G,B,D', 'EASY'),
('G#', 'MAJOR', 'G#', 'G#,C,D#', 'EASY'),
('A', 'MAJOR', 'A', 'A,C#,E', 'EASY'),
('A#', 'MAJOR', 'A#', 'A#,D,F', 'EASY'),
('B', 'MAJOR', 'B', 'B,D#,F#', 'EASY'),
-- Minor
('C', 'MINOR', 'Cm', 'C,D#,G', 'EASY'),
('C#', 'MINOR', 'C#m', 'C#,E,G#', 'EASY'),
('D', 'MINOR', 'Dm', 'D,F,A', 'EASY'),
('D#', 'MINOR', 'D#m', 'D#,F#,A#', 'EASY'),
('E', 'MINOR', 'Em', 'E,G,B', 'EASY'),
('F', 'MINOR', 'Fm', 'F,G#,C', 'EASY'),
('F#', 'MINOR', 'F#m', 'F#,A,C#', 'EASY'),
('G', 'MINOR', 'Gm', 'G,A#,D', 'EASY'),
('G#', 'MINOR', 'G#m', 'G#,B,D#', 'EASY'),
('A', 'MINOR', 'Am', 'A,C,E', 'EASY'),
('A#', 'MINOR', 'A#m', 'A#,C#,F', 'EASY'),
('B', 'MINOR', 'Bm', 'B,D,F#', 'EASY'),
-- Seventh
('C', 'SEVENTH', 'C7', 'C,E,G,A#', 'EASY'),
('C#', 'SEVENTH', 'C#7', 'C#,F,G#,B', 'EASY'),
('D', 'SEVENTH', 'D7', 'D,F#,A,C', 'EASY'),
('D#', 'SEVENTH', 'D#7', 'D#,G,A#,C#', 'EASY'),
('E', 'SEVENTH', 'E7', 'E,G#,B,D', 'EASY'),
('F', 'SEVENTH', 'F7', 'F,A,C,D#', 'EASY'),
('F#', 'SEVENTH', 'F#7', 'F#,A#,C#,E', 'EASY'),
('G', 'SEVENTH', 'G7', 'G,B,D,F', 'EASY'),
('G#', 'SEVENTH', 'G#7', 'G#,C,D#,F#', 'EASY'),
('A', 'SEVENTH', 'A7', 'A,C#,E,G', 'EASY'),
('A#', 'SEVENTH', 'A#7', 'A#,D,F,G#', 'EASY'),
('B', 'SEVENTH', 'B7', 'B,D#,F#,A', 'EASY'),
-- Minor Seventh
('C', 'MINOR_SEVENTH', 'Cm7', 'C,D#,G,A#', 'EASY'),
('C#', 'MINOR_SEVENTH', 'C#m7', 'C#,E,G#,B', 'EASY'),
('D', 'MINOR_SEVENTH', 'Dm7', 'D,F,A,C', 'EASY'),
('D#', 'MINOR_SEVENTH', 'D#m7', 'D#,F#,A#,C#', 'EASY'),
('E', 'MINOR_SEVENTH', 'Em7', 'E,G,B,D', 'EASY'),
('F', 'MINOR_SEVENTH', 'Fm7', 'F,G#,C,D#', 'EASY'),
('F#', 'MINOR_SEVENTH', 'F#m7', 'F#,A,C#,E', 'EASY'),
('G', 'MINOR_SEVENTH', 'Gm7', 'G,A#,D,F', 'EASY'),
('G#', 'MINOR_SEVENTH', 'G#m7', 'G#,B,D#,F#', 'EASY'),
('A', 'MINOR_SEVENTH', 'Am7', 'A,C,E,G', 'EASY'),
('A#', 'MINOR_SEVENTH', 'A#m7', 'A#,C#,F,G#', 'EASY'),
('B', 'MINOR_SEVENTH', 'Bm7', 'B,D,F#,A', 'EASY'),
-- Dim
('C', 'DIM', 'Cdim', 'C,D#,F#', 'EASY'),
('C#', 'DIM', 'C#dim', 'C#,E,G', 'EASY'),
('D', 'DIM', 'Ddim', 'D,F,G#', 'EASY'),
('D#', 'DIM', 'D#dim', 'D#,F#,A', 'EASY'),
('E', 'DIM', 'Edim', 'E,G,A#', 'EASY'),
('F', 'DIM', 'Fdim', 'F,G#,B', 'EASY'),
('F#', 'DIM', 'F#dim', 'F#,A,C', 'EASY'),
('G', 'DIM', 'Gdim', 'G,A#,C#', 'EASY'),
('G#', 'DIM', 'G#dim', 'G#,B,D', 'EASY'),
('A', 'DIM', 'Adim', 'A,C,D#', 'EASY'),
('A#', 'DIM', 'A#dim', 'A#,C#,E', 'EASY'),
('B', 'DIM', 'Bdim', 'B,D,F', 'EASY'),
-- Aug
('C', 'AUG', 'Caug', 'C,E,G#', 'EASY'),
('C#', 'AUG', 'C#aug', 'C#,F,A', 'EASY'),
('D', 'AUG', 'Daug', 'D,F#,A#', 'EASY'),
('D#', 'AUG', 'D#aug', 'D#,G,B', 'EASY'),
('E', 'AUG', 'Eaug', 'E,G#,C', 'EASY'),
('F', 'AUG', 'Faug', 'F,A,C#', 'EASY'),
('F#', 'AUG', 'F#aug', 'F#,A#,D', 'EASY'),
('G', 'AUG', 'Gaug', 'G,B,D#', 'EASY'),
('G#', 'AUG', 'G#aug', 'G#,C,E', 'EASY'),
('A', 'AUG', 'Aaug', 'A,C#,F', 'EASY'),
('A#', 'AUG', 'A#aug', 'A#,D,F#', 'EASY'),
('B', 'AUG', 'Baug', 'B,D#,G', 'EASY');

-- MEDIUM: Major Seventh, Major Ninth, Sixth, Minor Sixth, Sus2, Sus4, Ninth, Minor Ninth
INSERT IGNORE INTO quiz_chords (chordkey, chord_type, name, notes, difficulty) VALUES
-- Major Seventh
('C', 'MAJOR_SEVENTH', 'Cmaj7', 'C,E,G,B', 'MEDIUM'),
('C#', 'MAJOR_SEVENTH', 'C#maj7', 'C#,F,G#,C', 'MEDIUM'),
('D', 'MAJOR_SEVENTH', 'Dmaj7', 'D,F#,A,C#', 'MEDIUM'),
('D#', 'MAJOR_SEVENTH', 'D#maj7', 'D#,G,A#,D', 'MEDIUM'),
('E', 'MAJOR_SEVENTH', 'Emaj7', 'E,G#,B,D#', 'MEDIUM'),
('F', 'MAJOR_SEVENTH', 'Fmaj7', 'F,A,C,E', 'MEDIUM'),
('F#', 'MAJOR_SEVENTH', 'F#maj7', 'F#,A#,C#,F', 'MEDIUM'),
('G', 'MAJOR_SEVENTH', 'Gmaj7', 'G,B,D,F#', 'MEDIUM'),
('G#', 'MAJOR_SEVENTH', 'G#maj7', 'G#,C,D#,G', 'MEDIUM'),
('A', 'MAJOR_SEVENTH', 'Amaj7', 'A,C#,E,G#', 'MEDIUM'),
('A#', 'MAJOR_SEVENTH', 'A#maj7', 'A#,D,F,A', 'MEDIUM'),
('B', 'MAJOR_SEVENTH', 'Bmaj7', 'B,D#,F#,A#', 'MEDIUM'),
-- Major Ninth
('C', 'MAJOR_NINTH', 'Cmaj9', 'C,E,G,B,D', 'MEDIUM'),
('C#', 'MAJOR_NINTH', 'C#maj9', 'C#,F,G#,C,D#', 'MEDIUM'),
('D', 'MAJOR_NINTH', 'Dmaj9', 'D,F#,A,C#,E', 'MEDIUM'),
('D#', 'MAJOR_NINTH', 'D#maj9', 'D#,G,A#,D,F', 'MEDIUM'),
('E', 'MAJOR_NINTH', 'Emaj9', 'E,G#,B,D#,F#', 'MEDIUM'),
('F', 'MAJOR_NINTH', 'Fmaj9', 'F,A,C,E,G', 'MEDIUM'),
('F#', 'MAJOR_NINTH', 'F#maj9', 'F#,A#,C#,F,G#', 'MEDIUM'),
('G', 'MAJOR_NINTH', 'Gmaj9', 'G,B,D,F#,A', 'MEDIUM'),
('G#', 'MAJOR_NINTH', 'G#maj9', 'G#,C,D#,G,A#', 'MEDIUM'),
('A', 'MAJOR_NINTH', 'Amaj9', 'A,C#,E,G#,B', 'MEDIUM'),
('A#', 'MAJOR_NINTH', 'A#maj9', 'A#,D,F,A,C', 'MEDIUM'),
('B', 'MAJOR_NINTH', 'Bmaj9', 'B,D#,F#,A#,C#', 'MEDIUM'),
-- Sixth
('C', 'SIXTH', 'C6', 'C,E,G,A', 'MEDIUM'),
('C#', 'SIXTH', 'C#6', 'C#,F,G#,A#', 'MEDIUM'),
('D', 'SIXTH', 'D6', 'D,F#,A,B', 'MEDIUM'),
('D#', 'SIXTH', 'D#6', 'D#,G,A#,C', 'MEDIUM'),
('E', 'SIXTH', 'E6', 'E,G#,B,C#', 'MEDIUM'),
('F', 'SIXTH', 'F6', 'F,A,C,D', 'MEDIUM'),
('F#', 'SIXTH', 'F#6', 'F#,A#,C#,D#', 'MEDIUM'),
('G', 'SIXTH', 'G6', 'G,B,D,E', 'MEDIUM'),
('G#', 'SIXTH', 'G#6', 'G#,C,D#,F', 'MEDIUM'),
('A', 'SIXTH', 'A6', 'A,C#,E,F#', 'MEDIUM'),
('A#', 'SIXTH', 'A#6', 'A#,D,F,G', 'MEDIUM'),
('B', 'SIXTH', 'B6', 'B,D#,F#,G#', 'MEDIUM'),
-- Minor Sixth
('C', 'MINOR_SIXTH', 'Cm6', 'C,D#,G,A', 'MEDIUM'),
('C#', 'MINOR_SIXTH', 'C#m6', 'C#,E,G#,A#', 'MEDIUM'),
('D', 'MINOR_SIXTH', 'Dm6', 'D,F,A,B', 'MEDIUM'),
('D#', 'MINOR_SIXTH', 'D#m6', 'D#,F#,A#,C', 'MEDIUM'),
('E', 'MINOR_SIXTH', 'Em6', 'E,G,B,C#', 'MEDIUM'),
('F', 'MINOR_SIXTH', 'Fm6', 'F,G#,C,D', 'MEDIUM'),
('F#', 'MINOR_SIXTH', 'F#m6', 'F#,A,C#,D#', 'MEDIUM'),
('G', 'MINOR_SIXTH', 'Gm6', 'G,A#,D,E', 'MEDIUM'),
('G#', 'MINOR_SIXTH', 'G#m6', 'G#,B,D#,F', 'MEDIUM'),
('A', 'MINOR_SIXTH', 'Am6', 'A,C,E,F#', 'MEDIUM'),
('A#', 'MINOR_SIXTH', 'A#m6', 'A#,C#,F,G', 'MEDIUM'),
('B', 'MINOR_SIXTH', 'Bm6', 'B,D,F#,G#', 'MEDIUM'),
-- Sus2
('C', 'SUS2', 'Csus2', 'C,D,G', 'MEDIUM'),
('C#', 'SUS2', 'C#sus2', 'C#,D#,G#', 'MEDIUM'),
('D', 'SUS2', 'Dsus2', 'D,E,A', 'MEDIUM'),
('D#', 'SUS2', 'D#sus2', 'D#,F,A#', 'MEDIUM'),
('E', 'SUS2', 'Esus2', 'E,F#,B', 'MEDIUM'),
('F', 'SUS2', 'Fsus2', 'F,G,C', 'MEDIUM'),
('F#', 'SUS2', 'F#sus2', 'F#,G#,C#', 'MEDIUM'),
('G', 'SUS2', 'Gsus2', 'G,A,D', 'MEDIUM'),
('G#', 'SUS2', 'G#sus2', 'G#,A#,D#', 'MEDIUM'),
('A', 'SUS2', 'Asus2', 'A,B,E', 'MEDIUM'),
('A#', 'SUS2', 'A#sus2', 'A#,C,F', 'MEDIUM'),
('B', 'SUS2', 'Bsus2', 'B,C#,F#', 'MEDIUM'),
-- Sus4
('C', 'SUS4', 'Csus4', 'C,F,G', 'MEDIUM'),
('C#', 'SUS4', 'C#sus4', 'C#,F#,G#', 'MEDIUM'),
('D', 'SUS4', 'Dsus4', 'D,G,A', 'MEDIUM'),
('D#', 'SUS4', 'D#sus4', 'D#,G#,A#', 'MEDIUM'),
('E', 'SUS4', 'Esus4', 'E,A,B', 'MEDIUM'),
('F', 'SUS4', 'Fsus4', 'F,A#,C', 'MEDIUM'),
('F#', 'SUS4', 'F#sus4', 'F#,B,C#', 'MEDIUM'),
('G', 'SUS4', 'Gsus4', 'G,C,D', 'MEDIUM'),
('G#', 'SUS4', 'G#sus4', 'G#,C#,D#', 'MEDIUM'),
('A', 'SUS4', 'Asus4', 'A,D,E', 'MEDIUM'),
('A#', 'SUS4', 'A#sus4', 'A#,D#,F', 'MEDIUM'),
('B', 'SUS4', 'Bsus4', 'B,E,F#', 'MEDIUM'),
-- Ninth
('C', 'NINTH', 'C9', 'C,E,G,A#,D', 'MEDIUM'),
('C#', 'NINTH', 'C#9', 'C#,F,G#,B,D#', 'MEDIUM'),
('D', 'NINTH', 'D9', 'D,F#,A,C,E', 'MEDIUM'),
('D#', 'NINTH', 'D#9', 'D#,G,A#,C#,F', 'MEDIUM'),
('E', 'NINTH', 'E9', 'E,G#,B,D,F#', 'MEDIUM'),
('F', 'NINTH', 'F9', 'F,A,C,D#,G', 'MEDIUM'),
('F#', 'NINTH', 'F#9', 'F#,A#,C#,E,G#', 'MEDIUM'),
('G', 'NINTH', 'G9', 'G,B,D,F,A', 'MEDIUM'),
('G#', 'NINTH', 'G#9', 'G#,C,D#,F#,A#', 'MEDIUM'),
('A', 'NINTH', 'A9', 'A,C#,E,G,B', 'MEDIUM'),
('A#', 'NINTH', 'A#9', 'A#,D,F,G#,C', 'MEDIUM'),
('B', 'NINTH', 'B9', 'B,D#,F#,A,C#', 'MEDIUM'),
-- Minor Ninth
('C', 'MINOR_NINTH', 'Cm9', 'C,D#,G,A#,D', 'MEDIUM'),
('C#', 'MINOR_NINTH', 'C#m9', 'C#,E,G#,B,D#', 'MEDIUM'),
('D', 'MINOR_NINTH', 'Dm9', 'D,F,A,C,E', 'MEDIUM'),
('D#', 'MINOR_NINTH', 'D#m9', 'D#,F#,A#,C#,F', 'MEDIUM'),
('E', 'MINOR_NINTH', 'Em9', 'E,G,B,D,F#', 'MEDIUM'),
('F', 'MINOR_NINTH', 'Fm9', 'F,G#,C,D#,G', 'MEDIUM'),
('F#', 'MINOR_NINTH', 'F#m9', 'F#,A,C#,E,G#', 'MEDIUM'),
('G', 'MINOR_NINTH', 'Gm9', 'G,A#,D,F,A', 'MEDIUM'),
('G#', 'MINOR_NINTH', 'G#m9', 'G#,B,D#,F#,A#', 'MEDIUM'),
('A', 'MINOR_NINTH', 'Am9', 'A,C,E,G,B', 'MEDIUM'),
('A#', 'MINOR_NINTH', 'A#m9', 'A#,C#,F,G#,C', 'MEDIUM'),
('B', 'MINOR_NINTH', 'Bm9', 'B,D,F#,A,C#', 'MEDIUM');

-- HARD: Dim Seventh, Minor Seventh Flat5, Eleventh, Minor Eleventh, Thirteenth, Sixth Ninth
INSERT IGNORE INTO quiz_chords (chordkey, chord_type, name, notes, difficulty) VALUES
-- Dim Seventh
('C', 'DIM_SEVENTH', 'Cdim7', 'C,D#,F#,A', 'HARD'),
('C#', 'DIM_SEVENTH', 'C#dim7', 'C#,E,G,A#', 'HARD'),
('D', 'DIM_SEVENTH', 'Ddim7', 'D,F,G#,B', 'HARD'),
('D#', 'DIM_SEVENTH', 'D#dim7', 'D#,F#,A,C', 'HARD'),
('E', 'DIM_SEVENTH', 'Edim7', 'E,G,A#,C#', 'HARD'),
('F', 'DIM_SEVENTH', 'Fdim7', 'F,G#,B,D', 'HARD'),
('F#', 'DIM_SEVENTH', 'F#dim7', 'F#,A,C,D#', 'HARD'),
('G', 'DIM_SEVENTH', 'Gdim7', 'G,A#,C#,E', 'HARD'),
('G#', 'DIM_SEVENTH', 'G#dim7', 'G#,B,D,F', 'HARD'),
('A', 'DIM_SEVENTH', 'Adim7', 'A,C,D#,F#', 'HARD'),
('A#', 'DIM_SEVENTH', 'A#dim7', 'A#,C#,E,G', 'HARD'),
('B', 'DIM_SEVENTH', 'Bdim7', 'B,D,F,G#', 'HARD'),
-- Minor Seventh Flat5
('C', 'MINOR_SEVENTH_FLAT5', 'Cm7b5', 'C,D#,F#,A#', 'HARD'),
('C#', 'MINOR_SEVENTH_FLAT5', 'C#m7b5', 'C#,E,G,B', 'HARD'),
('D', 'MINOR_SEVENTH_FLAT5', 'Dm7b5', 'D,F,G#,C', 'HARD'),
('D#', 'MINOR_SEVENTH_FLAT5', 'D#m7b5', 'D#,F#,A,C#', 'HARD'),
('E', 'MINOR_SEVENTH_FLAT5', 'Em7b5', 'E,G,A#,D', 'HARD'),
('F', 'MINOR_SEVENTH_FLAT5', 'Fm7b5', 'F,G#,B,D#', 'HARD'),
('F#', 'MINOR_SEVENTH_FLAT5', 'F#m7b5', 'F#,A,C,E', 'HARD'),
('G', 'MINOR_SEVENTH_FLAT5', 'Gm7b5', 'G,A#,C#,F', 'HARD'),
('G#', 'MINOR_SEVENTH_FLAT5', 'G#m7b5', 'G#,B,D,F#', 'HARD'),
('A', 'MINOR_SEVENTH_FLAT5', 'Am7b5', 'A,C,D#,G', 'HARD'),
('A#', 'MINOR_SEVENTH_FLAT5', 'A#m7b5', 'A#,C#,E,G#', 'HARD'),
('B', 'MINOR_SEVENTH_FLAT5', 'Bm7b5', 'B,D,F,A', 'HARD'),
-- Eleventh
('C', 'ELEVENTH', 'C11', 'C,E,G,A#,D,F', 'HARD'),
('C#', 'ELEVENTH', 'C#11', 'C#,F,G#,B,D#,F#', 'HARD'),
('D', 'ELEVENTH', 'D11', 'D,F#,A,C,E,G', 'HARD'),
('D#', 'ELEVENTH', 'D#11', 'D#,G,A#,C#,F,G#', 'HARD'),
('E', 'ELEVENTH', 'E11', 'E,G#,B,D,F#,A', 'HARD'),
('F', 'ELEVENTH', 'F11', 'F,A,C,D#,G,A#', 'HARD'),
('F#', 'ELEVENTH', 'F#11', 'F#,A#,C#,E,G#,B', 'HARD'),
('G', 'ELEVENTH', 'G11', 'G,B,D,F,A,C', 'HARD'),
('G#', 'ELEVENTH', 'G#11', 'G#,C,D#,F#,A#,C#', 'HARD'),
('A', 'ELEVENTH', 'A11', 'A,C#,E,G,B,D', 'HARD'),
('A#', 'ELEVENTH', 'A#11', 'A#,D,F,G#,C,D#', 'HARD'),
('B', 'ELEVENTH', 'B11', 'B,D#,F#,A,C#,E', 'HARD'),
-- Minor Eleventh
('C', 'MINOR_ELEVENTH', 'Cm11', 'C,D#,G,A#,D,F', 'HARD'),
('C#', 'MINOR_ELEVENTH', 'C#m11', 'C#,E,G#,B,D#,F#', 'HARD'),
('D', 'MINOR_ELEVENTH', 'Dm11', 'D,F,A,C,E,G', 'HARD'),
('D#', 'MINOR_ELEVENTH', 'D#m11', 'D#,F#,A#,C#,F,G#', 'HARD'),
('E', 'MINOR_ELEVENTH', 'Em11', 'E,G,B,D,F#,A', 'HARD'),
('F', 'MINOR_ELEVENTH', 'Fm11', 'F,G#,C,D#,G,A#', 'HARD'),
('F#', 'MINOR_ELEVENTH', 'F#m11', 'F#,A,C#,E,G#,B', 'HARD'),
('G', 'MINOR_ELEVENTH', 'Gm11', 'G,A#,D,F,A,C', 'HARD'),
('G#', 'MINOR_ELEVENTH', 'G#m11', 'G#,B,D#,F#,A#,C#', 'HARD'),
('A', 'MINOR_ELEVENTH', 'Am11', 'A,C,E,G,B,D', 'HARD'),
('A#', 'MINOR_ELEVENTH', 'A#m11', 'A#,C#,F,G#,C,D#', 'HARD'),
('B', 'MINOR_ELEVENTH', 'Bm11', 'B,D,F#,A,C#,E', 'HARD'),
-- Thirteenth
('C', 'THIRTEENTH', 'C13', 'C,E,G,A#,D,F,A', 'HARD'),
('C#', 'THIRTEENTH', 'C#13', 'C#,F,G#,B,D#,F#,A#', 'HARD'),
('D', 'THIRTEENTH', 'D13', 'D,F#,A,C,E,G,B', 'HARD'),
('D#', 'THIRTEENTH', 'D#13', 'D#,G,A#,C#,F,G#,C', 'HARD'),
('E', 'THIRTEENTH', 'E13', 'E,G#,B,D,F#,A,C#', 'HARD'),
('F', 'THIRTEENTH', 'F13', 'F,A,C,D#,G,A#,D', 'HARD'),
('F#', 'THIRTEENTH', 'F#13', 'F#,A#,C#,E,G#,B,D#', 'HARD'),
('G', 'THIRTEENTH', 'G13', 'G,B,D,F,A,C,E', 'HARD'),
('G#', 'THIRTEENTH', 'G#13', 'G#,C,D#,F#,A#,C#,F', 'HARD'),
('A', 'THIRTEENTH', 'A13', 'A,C#,E,G,B,D,F#', 'HARD'),
('A#', 'THIRTEENTH', 'A#13', 'A#,D,F,G#,C,D#,G', 'HARD'),
('B', 'THIRTEENTH', 'B13', 'B,D#,F#,A,C#,E,G#', 'HARD'),
-- Sixth Ninth
('C', 'SIXTH_NINTH', 'C69', 'C,E,G,A,D', 'HARD'),
('C#', 'SIXTH_NINTH', 'C#69', 'C#,F,G#,A#,D#', 'HARD'),
('D', 'SIXTH_NINTH', 'D69', 'D,F#,A,B,E', 'HARD'),
('D#', 'SIXTH_NINTH', 'D#69', 'D#,G,A#,C,F', 'HARD'),
('E', 'SIXTH_NINTH', 'E69', 'E,G#,B,C#,F#', 'HARD'),
('F', 'SIXTH_NINTH', 'F69', 'F,A,C,D,G', 'HARD'),
('F#', 'SIXTH_NINTH', 'F#69', 'F#,A#,C#,D#,G#', 'HARD'),
('G', 'SIXTH_NINTH', 'G69', 'G,B,D,E,A', 'HARD'),
('G#', 'SIXTH_NINTH', 'G#69', 'G#,C,D#,F,A#', 'HARD'),
('A', 'SIXTH_NINTH', 'A69', 'A,C#,E,F#,B', 'HARD'),
('A#', 'SIXTH_NINTH', 'A#69', 'A#,D,F,G,C', 'HARD'),
('B', 'SIXTH_NINTH', 'B69', 'B,D#,F#,G#,C#', 'HARD');
