-- EASY: Major, Minor, Seventh, Minor Seventh, Dim, Aug (12키)
INSERT IGNORE INTO quiz_chords (chordkey, chord_type, name, notes, difficulty) VALUES
-- Major (12키)
('C', 'MAJOR', 'C Major', 'C,E,G', 'EASY'),
('C#', 'MAJOR', 'C# Major', 'C#,E#,G#', 'EASY'),
('D', 'MAJOR', 'D Major', 'D,F#,A', 'EASY'),
('Eb', 'MAJOR', 'Eb Major', 'Eb,G,Bb', 'EASY'),
('E', 'MAJOR', 'E Major', 'E,G#,B', 'EASY'),
('F', 'MAJOR', 'F Major', 'F,A,C', 'EASY'),
('F#', 'MAJOR', 'F# Major', 'F#,A#,C#', 'EASY'),
('G', 'MAJOR', 'G Major', 'G,B,D', 'EASY'),
('Ab', 'MAJOR', 'Ab Major', 'Ab,C,Eb', 'EASY'),
('A', 'MAJOR', 'A Major', 'A,C#,E', 'EASY'),
('Bb', 'MAJOR', 'Bb Major', 'Bb,D,F', 'EASY'),
('B', 'MAJOR', 'B Major', 'B,D#,F#', 'EASY'),
-- Minor (12키)
('C', 'MINOR', 'C Minor', 'C,Eb,G', 'EASY'),
('C#', 'MINOR', 'C# Minor', 'C#,E,G#', 'EASY'),
('D', 'MINOR', 'D Minor', 'D,F,A', 'EASY'),
('Eb', 'MINOR', 'Eb Minor', 'Eb,Gb,Bb', 'EASY'),
('E', 'MINOR', 'E Minor', 'E,G,B', 'EASY'),
('F', 'MINOR', 'F Minor', 'F,Ab,C', 'EASY'),
('F#', 'MINOR', 'F# Minor', 'F#,A,C#', 'EASY'),
('G', 'MINOR', 'G Minor', 'G,Bb,D', 'EASY'),
('Ab', 'MINOR', 'Ab Minor', 'Ab,Cb,Eb', 'EASY'),
('A', 'MINOR', 'A Minor', 'A,C,E', 'EASY'),
('Bb', 'MINOR', 'Bb Minor', 'Bb,Db,F', 'EASY'),
('B', 'MINOR', 'B Minor', 'B,D,F#', 'EASY'),
-- Seventh (12키)
('C', 'SEVENTH', 'C7', 'C,E,G,Bb', 'EASY'),
('C#', 'SEVENTH', 'C#7', 'C#,E#,G#,B', 'EASY'),
('D', 'SEVENTH', 'D7', 'D,F#,A,C', 'EASY'),
('Eb', 'SEVENTH', 'Eb7', 'Eb,G,Bb,Db', 'EASY'),
('E', 'SEVENTH', 'E7', 'E,G#,B,D', 'EASY'),
('F', 'SEVENTH', 'F7', 'F,A,C,Eb', 'EASY'),
('F#', 'SEVENTH', 'F#7', 'F#,A#,C#,E', 'EASY'),
('G', 'SEVENTH', 'G7', 'G,B,D,F', 'EASY'),
('Ab', 'SEVENTH', 'Ab7', 'Ab,C,Eb,Gb', 'EASY'),
('A', 'SEVENTH', 'A7', 'A,C#,E,G', 'EASY'),
('Bb', 'SEVENTH', 'Bb7', 'Bb,D,F,Ab', 'EASY'),
('B', 'SEVENTH', 'B7', 'B,D#,F#,A', 'EASY'),
-- Minor Seventh (12키)
('C', 'MINOR_SEVENTH', 'Cm7', 'C,Eb,G,Bb', 'EASY'),
('C#', 'MINOR_SEVENTH', 'C#m7', 'C#,E,G#,B', 'EASY'),
('D', 'MINOR_SEVENTH', 'Dm7', 'D,F,A,C', 'EASY'),
('Eb', 'MINOR_SEVENTH', 'Ebm7', 'Eb,Gb,Bb,Db', 'EASY'),
('E', 'MINOR_SEVENTH', 'Em7', 'E,G,B,D', 'EASY'),
('F', 'MINOR_SEVENTH', 'Fm7', 'F,Ab,C,Eb', 'EASY'),
('F#', 'MINOR_SEVENTH', 'F#m7', 'F#,A,C#,E', 'EASY'),
('G', 'MINOR_SEVENTH', 'Gm7', 'G,Bb,D,F', 'EASY'),
('Ab', 'MINOR_SEVENTH', 'Abm7', 'Ab,Cb,Eb,Gb', 'EASY'),
('A', 'MINOR_SEVENTH', 'Am7', 'A,C,E,G', 'EASY'),
('Bb', 'MINOR_SEVENTH', 'Bbm7', 'Bb,Db,F,Ab', 'EASY'),
('B', 'MINOR_SEVENTH', 'Bm7', 'B,D,F#,A', 'EASY'),
-- Dim (12키)
('C', 'DIM', 'Cdim', 'C,Eb,Gb', 'EASY'),
('C#', 'DIM', 'C#dim', 'C#,E,G', 'EASY'),
('D', 'DIM', 'Ddim', 'D,F,Ab', 'EASY'),
('Eb', 'DIM', 'Ebdim', 'Eb,Gb,Bbb', 'EASY'),
('E', 'DIM', 'Edim', 'E,G,Bb', 'EASY'),
('F', 'DIM', 'Fdim', 'F,Ab,Cb', 'EASY'),
('F#', 'DIM', 'F#dim', 'F#,A,C', 'EASY'),
('G', 'DIM', 'Gdim', 'G,Bb,Db', 'EASY'),
('Ab', 'DIM', 'Abdim', 'Ab,Cb,Ebb', 'EASY'),
('A', 'DIM', 'Adim', 'A,C,Eb', 'EASY'),
('Bb', 'DIM', 'Bbdim', 'Bb,Db,Fb', 'EASY'),
('B', 'DIM', 'Bdim', 'B,D,F', 'EASY'),
-- Aug (12키)
('C', 'AUG', 'Caug', 'C,E,G#', 'EASY'),
('C#', 'AUG', 'C#aug', 'C#,E#,A', 'EASY'),
('D', 'AUG', 'Daug', 'D,F#,A#', 'EASY'),
('Eb', 'AUG', 'Ebaug', 'Eb,G,B', 'EASY'),
('E', 'AUG', 'Eaug', 'E,G#,B#', 'EASY'),
('F', 'AUG', 'Faug', 'F,A,C#', 'EASY'),
('F#', 'AUG', 'F#aug', 'F#,A#,D', 'EASY'),
('G', 'AUG', 'Gaug', 'G,B,D#', 'EASY'),
('Ab', 'AUG', 'Abaug', 'Ab,C,E', 'EASY'),
('A', 'AUG', 'Aaug', 'A,C#,E#', 'EASY'),
('Bb', 'AUG', 'Bbaug', 'Bb,D,F#', 'EASY'),
('B', 'AUG', 'Baug', 'B,D#,G', 'EASY'),

-- MEDIUM: Maj7, Maj9, 6th, m6, sus2, sus4, 9th, m9 (12키)
-- Major Seventh (12키)
('C', 'MAJOR_SEVENTH', 'Cmaj7', 'C,E,G,B', 'MEDIUM'),
('C#', 'MAJOR_SEVENTH', 'C#maj7', 'C#,E#,G#,B#', 'MEDIUM'),
('D', 'MAJOR_SEVENTH', 'Dmaj7', 'D,F#,A,C#', 'MEDIUM'),
('Eb', 'MAJOR_SEVENTH', 'Ebmaj7', 'Eb,G,Bb,D', 'MEDIUM'),
('E', 'MAJOR_SEVENTH', 'Emaj7', 'E,G#,B,D#', 'MEDIUM'),
('F', 'MAJOR_SEVENTH', 'Fmaj7', 'F,A,C,E', 'MEDIUM'),
('F#', 'MAJOR_SEVENTH', 'F#maj7', 'F#,A#,C#,E#', 'MEDIUM'),
('G', 'MAJOR_SEVENTH', 'Gmaj7', 'G,B,D,F#', 'MEDIUM'),
('Ab', 'MAJOR_SEVENTH', 'Abmaj7', 'Ab,C,Eb,G', 'MEDIUM'),
('A', 'MAJOR_SEVENTH', 'Amaj7', 'A,C#,E,G#', 'MEDIUM'),
('Bb', 'MAJOR_SEVENTH', 'Bbmaj7', 'Bb,D,F,A', 'MEDIUM'),
('B', 'MAJOR_SEVENTH', 'Bmaj7', 'B,D#,F#,A#', 'MEDIUM'),
-- Major Ninth (12키)
('C', 'MAJOR_NINTH', 'Cmaj9', 'C,E,G,B,D', 'MEDIUM'),
('C#', 'MAJOR_NINTH', 'C#maj9', 'C#,E#,G#,B#,D#', 'MEDIUM'),
('D', 'MAJOR_NINTH', 'Dmaj9', 'D,F#,A,C#,E', 'MEDIUM'),
('Eb', 'MAJOR_NINTH', 'Ebmaj9', 'Eb,G,Bb,D,F', 'MEDIUM'),
('E', 'MAJOR_NINTH', 'Emaj9', 'E,G#,B,D#,F#', 'MEDIUM'),
('F', 'MAJOR_NINTH', 'Fmaj9', 'F,A,C,E,G', 'MEDIUM'),
('F#', 'MAJOR_NINTH', 'F#maj9', 'F#,A#,C#,E#,G#', 'MEDIUM'),
('G', 'MAJOR_NINTH', 'Gmaj9', 'G,B,D,F#,A', 'MEDIUM'),
('Ab', 'MAJOR_NINTH', 'Abmaj9', 'Ab,C,Eb,G,Bb', 'MEDIUM'),
('A', 'MAJOR_NINTH', 'Amaj9', 'A,C#,E,G#,B', 'MEDIUM'),
('Bb', 'MAJOR_NINTH', 'Bbmaj9', 'Bb,D,F,A,C', 'MEDIUM'),
('B', 'MAJOR_NINTH', 'Bmaj9', 'B,D#,F#,A#,C#', 'MEDIUM'),
-- Sixth (12키)
('C', 'SIXTH', 'C6', 'C,E,G,A', 'MEDIUM'),
('C#', 'SIXTH', 'C#6', 'C#,E#,G#,A#', 'MEDIUM'),
('D', 'SIXTH', 'D6', 'D,F#,A,B', 'MEDIUM'),
('Eb', 'SIXTH', 'Eb6', 'Eb,G,Bb,C', 'MEDIUM'),
('E', 'SIXTH', 'E6', 'E,G#,B,C#', 'MEDIUM'),
('F', 'SIXTH', 'F6', 'F,A,C,D', 'MEDIUM'),
('F#', 'SIXTH', 'F#6', 'F#,A#,C#,D#', 'MEDIUM'),
('G', 'SIXTH', 'G6', 'G,B,D,E', 'MEDIUM'),
('Ab', 'SIXTH', 'Ab6', 'Ab,C,Eb,F', 'MEDIUM'),
('A', 'SIXTH', 'A6', 'A,C#,E,F#', 'MEDIUM'),
('Bb', 'SIXTH', 'Bb6', 'Bb,D,F,G', 'MEDIUM'),
('B', 'SIXTH', 'B6', 'B,D#,F#,G#', 'MEDIUM'),
-- Minor Sixth (12키)
('C', 'MINOR_SIXTH', 'Cm6', 'C,Eb,G,A', 'MEDIUM'),
('C#', 'MINOR_SIXTH', 'C#m6', 'C#,E,G#,A#', 'MEDIUM'),
('D', 'MINOR_SIXTH', 'Dm6', 'D,F,A,B', 'MEDIUM'),
('Eb', 'MINOR_SIXTH', 'Ebm6', 'Eb,Gb,Bb,C', 'MEDIUM'),
('E', 'MINOR_SIXTH', 'Em6', 'E,G,B,C#', 'MEDIUM'),
('F', 'MINOR_SIXTH', 'Fm6', 'F,Ab,C,D', 'MEDIUM'),
('F#', 'MINOR_SIXTH', 'F#m6', 'F#,A,C#,D#', 'MEDIUM'),
('G', 'MINOR_SIXTH', 'Gm6', 'G,Bb,D,E', 'MEDIUM'),
('Ab', 'MINOR_SIXTH', 'Abm6', 'Ab,Cb,Eb,F', 'MEDIUM'),
('A', 'MINOR_SIXTH', 'Am6', 'A,C,E,F#', 'MEDIUM'),
('Bb', 'MINOR_SIXTH', 'Bbm6', 'Bb,Db,F,G', 'MEDIUM'),
('B', 'MINOR_SIXTH', 'Bm6', 'B,D,F#,G#', 'MEDIUM'),
-- Sus2 (12키)
('C', 'SUS2', 'Csus2', 'C,D,G', 'MEDIUM'),
('C#', 'SUS2', 'C#sus2', 'C#,D#,G#', 'MEDIUM'),
('D', 'SUS2', 'Dsus2', 'D,E,A', 'MEDIUM'),
('Eb', 'SUS2', 'Ebsus2', 'Eb,F,Bb', 'MEDIUM'),
('E', 'SUS2', 'Esus2', 'E,F#,B', 'MEDIUM'),
('F', 'SUS2', 'Fsus2', 'F,G,C', 'MEDIUM'),
('F#', 'SUS2', 'F#sus2', 'F#,G#,C#', 'MEDIUM'),
('G', 'SUS2', 'Gsus2', 'G,A,D', 'MEDIUM'),
('Ab', 'SUS2', 'Absus2', 'Ab,Bb,Eb', 'MEDIUM'),
('A', 'SUS2', 'Asus2', 'A,B,E', 'MEDIUM'),
('Bb', 'SUS2', 'Bbsus2', 'Bb,C,F', 'MEDIUM'),
('B', 'SUS2', 'Bsus2', 'B,C#,F#', 'MEDIUM'),
-- Sus4 (12키)
('C', 'SUS4', 'Csus4', 'C,F,G', 'MEDIUM'),
('C#', 'SUS4', 'C#sus4', 'C#,F#,G#', 'MEDIUM'),
('D', 'SUS4', 'Dsus4', 'D,G,A', 'MEDIUM'),
('Eb', 'SUS4', 'Ebsus4', 'Eb,Ab,Bb', 'MEDIUM'),
('E', 'SUS4', 'Esus4', 'E,A,B', 'MEDIUM'),
('F', 'SUS4', 'Fsus4', 'F,Bb,C', 'MEDIUM'),
('F#', 'SUS4', 'F#sus4', 'F#,B,C#', 'MEDIUM'),
('G', 'SUS4', 'Gsus4', 'G,C,D', 'MEDIUM'),
('Ab', 'SUS4', 'Absus4', 'Ab,Db,Eb', 'MEDIUM'),
('A', 'SUS4', 'Asus4', 'A,D,E', 'MEDIUM'),
('Bb', 'SUS4', 'Bbsus4', 'Bb,Eb,F', 'MEDIUM'),
('B', 'SUS4', 'Bsus4', 'B,E,F#', 'MEDIUM'),
-- Ninth (12키)
('C', 'NINTH', 'C9', 'C,E,G,Bb,D', 'MEDIUM'),
('C#', 'NINTH', 'C#9', 'C#,E#,G#,B,D#', 'MEDIUM'),
('D', 'NINTH', 'D9', 'D,F#,A,C,E', 'MEDIUM'),
('Eb', 'NINTH', 'Eb9', 'Eb,G,Bb,Db,F', 'MEDIUM'),
('E', 'NINTH', 'E9', 'E,G#,B,D,F#', 'MEDIUM'),
('F', 'NINTH', 'F9', 'F,A,C,Eb,G', 'MEDIUM'),
('F#', 'NINTH', 'F#9', 'F#,A#,C#,E,G#', 'MEDIUM'),
('G', 'NINTH', 'G9', 'G,B,D,F,A', 'MEDIUM'),
('Ab', 'NINTH', 'Ab9', 'Ab,C,Eb,Gb,Bb', 'MEDIUM'),
('A', 'NINTH', 'A9', 'A,C#,E,G,B', 'MEDIUM'),
('Bb', 'NINTH', 'Bb9', 'Bb,D,F,Ab,C', 'MEDIUM'),
('B', 'NINTH', 'B9', 'B,D#,F#,A,C#', 'MEDIUM'),
-- Minor Ninth (12키)
('C', 'MINOR_NINTH', 'Cm9', 'C,Eb,G,Bb,D', 'MEDIUM'),
('C#', 'MINOR_NINTH', 'C#m9', 'C#,E,G#,B,D#', 'MEDIUM'),
('D', 'MINOR_NINTH', 'Dm9', 'D,F,A,C,E', 'MEDIUM'),
('Eb', 'MINOR_NINTH', 'Ebm9', 'Eb,Gb,Bb,Db,F', 'MEDIUM'),
('E', 'MINOR_NINTH', 'Em9', 'E,G,B,D,F#', 'MEDIUM'),
('F', 'MINOR_NINTH', 'Fm9', 'F,Ab,C,Eb,G', 'MEDIUM'),
('F#', 'MINOR_NINTH', 'F#m9', 'F#,A,C#,E,G#', 'MEDIUM'),
('G', 'MINOR_NINTH', 'Gm9', 'G,Bb,D,F,A', 'MEDIUM'),
('Ab', 'MINOR_NINTH', 'Abm9', 'Ab,Cb,Eb,Gb,Bb', 'MEDIUM'),
('A', 'MINOR_NINTH', 'Am9', 'A,C,E,G,B', 'MEDIUM'),
('Bb', 'MINOR_NINTH', 'Bbm9', 'Bb,Db,F,Ab,C', 'MEDIUM'),
('B', 'MINOR_NINTH', 'Bm9', 'B,D,F#,A,C#', 'MEDIUM'),

-- HARD: dim7, m7b5, 11th, m11, 13th, 6/9 (12키)
-- Dim Seventh (12키)
('C', 'DIM_SEVENTH', 'Cdim7', 'C,Eb,Gb,Bbb', 'HARD'),
('C#', 'DIM_SEVENTH', 'C#dim7', 'C#,E,G,Bb', 'HARD'),
('D', 'DIM_SEVENTH', 'Ddim7', 'D,F,Ab,Cb', 'HARD'),
('Eb', 'DIM_SEVENTH', 'Ebdim7', 'Eb,Gb,Bbb,Dbb', 'HARD'),
('E', 'DIM_SEVENTH', 'Edim7', 'E,G,Bb,Db', 'HARD'),
('F', 'DIM_SEVENTH', 'Fdim7', 'F,Ab,Cb,Ebb', 'HARD'),
('F#', 'DIM_SEVENTH', 'F#dim7', 'F#,A,C,Eb', 'HARD'),
('G', 'DIM_SEVENTH', 'Gdim7', 'G,Bb,Db,Fb', 'HARD'),
('Ab', 'DIM_SEVENTH', 'Abdim7', 'Ab,Cb,Ebb,Gbb', 'HARD'),
('A', 'DIM_SEVENTH', 'Adim7', 'A,C,Eb,Gb', 'HARD'),
('Bb', 'DIM_SEVENTH', 'Bbdim7', 'Bb,Db,Fb,Abb', 'HARD'),
('B', 'DIM_SEVENTH', 'Bdim7', 'B,D,F,Ab', 'HARD'),
-- Minor Seventh Flat 5 (12키)
('C', 'MINOR_SEVENTH_FLAT5', 'Cm7b5', 'C,Eb,Gb,Bb', 'HARD'),
('C#', 'MINOR_SEVENTH_FLAT5', 'C#m7b5', 'C#,E,G,B', 'HARD'),
('D', 'MINOR_SEVENTH_FLAT5', 'Dm7b5', 'D,F,Ab,C', 'HARD'),
('Eb', 'MINOR_SEVENTH_FLAT5', 'Ebm7b5', 'Eb,Gb,Bbb,Db', 'HARD'),
('E', 'MINOR_SEVENTH_FLAT5', 'Em7b5', 'E,G,Bb,D', 'HARD'),
('F', 'MINOR_SEVENTH_FLAT5', 'Fm7b5', 'F,Ab,Cb,Eb', 'HARD'),
('F#', 'MINOR_SEVENTH_FLAT5', 'F#m7b5', 'F#,A,C,E', 'HARD'),
('G', 'MINOR_SEVENTH_FLAT5', 'Gm7b5', 'G,Bb,Db,F', 'HARD'),
('Ab', 'MINOR_SEVENTH_FLAT5', 'Abm7b5', 'Ab,Cb,Ebb,Gb', 'HARD'),
('A', 'MINOR_SEVENTH_FLAT5', 'Am7b5', 'A,C,Eb,G', 'HARD'),
('Bb', 'MINOR_SEVENTH_FLAT5', 'Bbm7b5', 'Bb,Db,Fb,Ab', 'HARD'),
('B', 'MINOR_SEVENTH_FLAT5', 'Bm7b5', 'B,D,F,A', 'HARD'),
-- Eleventh (12키)
('C', 'ELEVENTH', 'C11', 'C,E,G,Bb,D,F', 'HARD'),
('C#', 'ELEVENTH', 'C#11', 'C#,E#,G#,B,D#,F#', 'HARD'),
('D', 'ELEVENTH', 'D11', 'D,F#,A,C,E,G', 'HARD'),
('Eb', 'ELEVENTH', 'Eb11', 'Eb,G,Bb,Db,F,Ab', 'HARD'),
('E', 'ELEVENTH', 'E11', 'E,G#,B,D,F#,A', 'HARD'),
('F', 'ELEVENTH', 'F11', 'F,A,C,Eb,G,Bb', 'HARD'),
('F#', 'ELEVENTH', 'F#11', 'F#,A#,C#,E,G#,B', 'HARD'),
('G', 'ELEVENTH', 'G11', 'G,B,D,F,A,C', 'HARD'),
('Ab', 'ELEVENTH', 'Ab11', 'Ab,C,Eb,Gb,Bb,Db', 'HARD'),
('A', 'ELEVENTH', 'A11', 'A,C#,E,G,B,D', 'HARD'),
('Bb', 'ELEVENTH', 'Bb11', 'Bb,D,F,Ab,C,Eb', 'HARD'),
('B', 'ELEVENTH', 'B11', 'B,D#,F#,A,C#,E', 'HARD'),
-- Minor Eleventh (12키)
('C', 'MINOR_ELEVENTH', 'Cm11', 'C,Eb,G,Bb,D,F', 'HARD'),
('C#', 'MINOR_ELEVENTH', 'C#m11', 'C#,E,G#,B,D#,F#', 'HARD'),
('D', 'MINOR_ELEVENTH', 'Dm11', 'D,F,A,C,E,G', 'HARD'),
('Eb', 'MINOR_ELEVENTH', 'Ebm11', 'Eb,Gb,Bb,Db,F,Ab', 'HARD'),
('E', 'MINOR_ELEVENTH', 'Em11', 'E,G,B,D,F#,A', 'HARD'),
('F', 'MINOR_ELEVENTH', 'Fm11', 'F,Ab,C,Eb,G,Bb', 'HARD'),
('F#', 'MINOR_ELEVENTH', 'F#m11', 'F#,A,C#,E,G#,B', 'HARD'),
('G', 'MINOR_ELEVENTH', 'Gm11', 'G,Bb,D,F,A,C', 'HARD'),
('Ab', 'MINOR_ELEVENTH', 'Abm11', 'Ab,Cb,Eb,Gb,Bb,Db', 'HARD'),
('A', 'MINOR_ELEVENTH', 'Am11', 'A,C,E,G,B,D', 'HARD'),
('Bb', 'MINOR_ELEVENTH', 'Bbm11', 'Bb,Db,F,Ab,C,Eb', 'HARD'),
('B', 'MINOR_ELEVENTH', 'Bm11', 'B,D,F#,A,C#,E', 'HARD'),
-- Thirteenth (12키)
('C', 'THIRTEENTH', 'C13', 'C,E,G,Bb,D,A', 'HARD'),
('C#', 'THIRTEENTH', 'C#13', 'C#,E#,G#,B,D#,A#', 'HARD'),
('D', 'THIRTEENTH', 'D13', 'D,F#,A,C,E,B', 'HARD'),
('Eb', 'THIRTEENTH', 'Eb13', 'Eb,G,Bb,Db,F,C', 'HARD'),
('E', 'THIRTEENTH', 'E13', 'E,G#,B,D,F#,C#', 'HARD'),
('F', 'THIRTEENTH', 'F13', 'F,A,C,Eb,G,D', 'HARD'),
('F#', 'THIRTEENTH', 'F#13', 'F#,A#,C#,E,G#,D#', 'HARD'),
('G', 'THIRTEENTH', 'G13', 'G,B,D,F,A,E', 'HARD'),
('Ab', 'THIRTEENTH', 'Ab13', 'Ab,C,Eb,Gb,Bb,F', 'HARD'),
('A', 'THIRTEENTH', 'A13', 'A,C#,E,G,B,F#', 'HARD'),
('Bb', 'THIRTEENTH', 'Bb13', 'Bb,D,F,Ab,C,G', 'HARD'),
('B', 'THIRTEENTH', 'B13', 'B,D#,F#,A,C#,G#', 'HARD'),
-- Sixth Ninth (12키)
('C', 'SIXTH_NINTH', 'C6/9', 'C,E,G,A,D', 'HARD'),
('C#', 'SIXTH_NINTH', 'C#6/9', 'C#,E#,G#,A#,D#', 'HARD'),
('D', 'SIXTH_NINTH', 'D6/9', 'D,F#,A,B,E', 'HARD'),
('Eb', 'SIXTH_NINTH', 'Eb6/9', 'Eb,G,Bb,C,F', 'HARD'),
('E', 'SIXTH_NINTH', 'E6/9', 'E,G#,B,C#,F#', 'HARD'),
('F', 'SIXTH_NINTH', 'F6/9', 'F,A,C,D,G', 'HARD'),
('F#', 'SIXTH_NINTH', 'F#6/9', 'F#,A#,C#,D#,G#', 'HARD'),
('G', 'SIXTH_NINTH', 'G6/9', 'G,B,D,E,A', 'HARD'),
('Ab', 'SIXTH_NINTH', 'Ab6/9', 'Ab,C,Eb,F,Bb', 'HARD'),
('A', 'SIXTH_NINTH', 'A6/9', 'A,C#,E,F#,B', 'HARD'),
('Bb', 'SIXTH_NINTH', 'Bb6/9', 'Bb,D,F,G,C', 'HARD'),
('B', 'SIXTH_NINTH', 'B6/9', 'B,D#,F#,G#,C#', 'HARD'),

-- MEDIUM 추가: Minor Major Seventh (12키)
('C', 'MINOR_MAJOR_SEVENTH', 'CmM7', 'C,Eb,G,B', 'MEDIUM'),
('C#', 'MINOR_MAJOR_SEVENTH', 'C#mM7', 'C#,E,G#,B#', 'MEDIUM'),
('D', 'MINOR_MAJOR_SEVENTH', 'DmM7', 'D,F,A,C#', 'MEDIUM'),
('Eb', 'MINOR_MAJOR_SEVENTH', 'EbmM7', 'Eb,Gb,Bb,D', 'MEDIUM'),
('E', 'MINOR_MAJOR_SEVENTH', 'EmM7', 'E,G,B,D#', 'MEDIUM'),
('F', 'MINOR_MAJOR_SEVENTH', 'FmM7', 'F,Ab,C,E', 'MEDIUM'),
('F#', 'MINOR_MAJOR_SEVENTH', 'F#mM7', 'F#,A,C#,E#', 'MEDIUM'),
('G', 'MINOR_MAJOR_SEVENTH', 'GmM7', 'G,Bb,D,F#', 'MEDIUM'),
('Ab', 'MINOR_MAJOR_SEVENTH', 'AbmM7', 'Ab,Cb,Eb,G', 'MEDIUM'),
('A', 'MINOR_MAJOR_SEVENTH', 'AmM7', 'A,C,E,G#', 'MEDIUM'),
('Bb', 'MINOR_MAJOR_SEVENTH', 'BbmM7', 'Bb,Db,F,A', 'MEDIUM'),
('B', 'MINOR_MAJOR_SEVENTH', 'BmM7', 'B,D,F#,A#', 'MEDIUM'),
-- MEDIUM 추가: Add9 (12키)
('C', 'ADD9', 'Cadd9', 'C,E,G,D', 'MEDIUM'),
('C#', 'ADD9', 'C#add9', 'C#,E#,G#,D#', 'MEDIUM'),
('D', 'ADD9', 'Dadd9', 'D,F#,A,E', 'MEDIUM'),
('Eb', 'ADD9', 'Ebadd9', 'Eb,G,Bb,F', 'MEDIUM'),
('E', 'ADD9', 'Eadd9', 'E,G#,B,F#', 'MEDIUM'),
('F', 'ADD9', 'Fadd9', 'F,A,C,G', 'MEDIUM'),
('F#', 'ADD9', 'F#add9', 'F#,A#,C#,G#', 'MEDIUM'),
('G', 'ADD9', 'Gadd9', 'G,B,D,A', 'MEDIUM'),
('Ab', 'ADD9', 'Abadd9', 'Ab,C,Eb,Bb', 'MEDIUM'),
('A', 'ADD9', 'Aadd9', 'A,C#,E,B', 'MEDIUM'),
('Bb', 'ADD9', 'Bbadd9', 'Bb,D,F,C', 'MEDIUM'),
('B', 'ADD9', 'Badd9', 'B,D#,F#,C#', 'MEDIUM'),

-- HARD 추가: 7alt (12키)
('C', 'SEVENTH_ALT', 'C7alt', 'C,E,G#,Bb', 'HARD'),
('C#', 'SEVENTH_ALT', 'C#7alt', 'C#,E#,A,B', 'HARD'),
('D', 'SEVENTH_ALT', 'D7alt', 'D,F#,A#,C', 'HARD'),
('Eb', 'SEVENTH_ALT', 'Eb7alt', 'Eb,G,B,Db', 'HARD'),
('E', 'SEVENTH_ALT', 'E7alt', 'E,G#,B#,D', 'HARD'),
('F', 'SEVENTH_ALT', 'F7alt', 'F,A,C#,Eb', 'HARD'),
('F#', 'SEVENTH_ALT', 'F#7alt', 'F#,A#,D,E', 'HARD'),
('G', 'SEVENTH_ALT', 'G7alt', 'G,B,D#,F', 'HARD'),
('Ab', 'SEVENTH_ALT', 'Ab7alt', 'Ab,C,E,Gb', 'HARD'),
('A', 'SEVENTH_ALT', 'A7alt', 'A,C#,E#,G', 'HARD'),
('Bb', 'SEVENTH_ALT', 'Bb7alt', 'Bb,D,F#,Ab', 'HARD'),
('B', 'SEVENTH_ALT', 'B7alt', 'B,D#,G,A', 'HARD'),
-- HARD 추가: 7#9 (12키)
('C', 'SEVENTH_SHARP9', 'C7#9', 'C,E,G,Bb,D#', 'HARD'),
('C#', 'SEVENTH_SHARP9', 'C#7#9', 'C#,E#,G#,B,E', 'HARD'),
('D', 'SEVENTH_SHARP9', 'D7#9', 'D,F#,A,C,E#', 'HARD'),
('Eb', 'SEVENTH_SHARP9', 'Eb7#9', 'Eb,G,Bb,Db,F#', 'HARD'),
('E', 'SEVENTH_SHARP9', 'E7#9', 'E,G#,B,D,G', 'HARD'),
('F', 'SEVENTH_SHARP9', 'F7#9', 'F,A,C,Eb,G#', 'HARD'),
('F#', 'SEVENTH_SHARP9', 'F#7#9', 'F#,A#,C#,E,A', 'HARD'),
('G', 'SEVENTH_SHARP9', 'G7#9', 'G,B,D,F,A#', 'HARD'),
('Ab', 'SEVENTH_SHARP9', 'Ab7#9', 'Ab,C,Eb,Gb,B', 'HARD'),
('A', 'SEVENTH_SHARP9', 'A7#9', 'A,C#,E,G,B#', 'HARD'),
('Bb', 'SEVENTH_SHARP9', 'Bb7#9', 'Bb,D,F,Ab,C#', 'HARD'),
('B', 'SEVENTH_SHARP9', 'B7#9', 'B,D#,F#,A,D', 'HARD'),
-- HARD 추가: 7b9 (12키)
('C', 'SEVENTH_FLAT9', 'C7b9', 'C,E,G,Bb,Db', 'HARD'),
('C#', 'SEVENTH_FLAT9', 'C#7b9', 'C#,E#,G#,B,D', 'HARD'),
('D', 'SEVENTH_FLAT9', 'D7b9', 'D,F#,A,C,Eb', 'HARD'),
('Eb', 'SEVENTH_FLAT9', 'Eb7b9', 'Eb,G,Bb,Db,Fb', 'HARD'),
('E', 'SEVENTH_FLAT9', 'E7b9', 'E,G#,B,D,F', 'HARD'),
('F', 'SEVENTH_FLAT9', 'F7b9', 'F,A,C,Eb,Gb', 'HARD'),
('F#', 'SEVENTH_FLAT9', 'F#7b9', 'F#,A#,C#,E,G', 'HARD'),
('G', 'SEVENTH_FLAT9', 'G7b9', 'G,B,D,F,Ab', 'HARD'),
('Ab', 'SEVENTH_FLAT9', 'Ab7b9', 'Ab,C,Eb,Gb,Bbb', 'HARD'),
('A', 'SEVENTH_FLAT9', 'A7b9', 'A,C#,E,G,Bb', 'HARD'),
('Bb', 'SEVENTH_FLAT9', 'Bb7b9', 'Bb,D,F,Ab,Cb', 'HARD'),
('B', 'SEVENTH_FLAT9', 'B7b9', 'B,D#,F#,A,C', 'HARD'),
-- HARD 추가: 7#5 (12키)
('C', 'SEVENTH_SHARP5', 'C7#5', 'C,E,G#,Bb', 'HARD'),
('C#', 'SEVENTH_SHARP5', 'C#7#5', 'C#,E#,A,B', 'HARD'),
('D', 'SEVENTH_SHARP5', 'D7#5', 'D,F#,A#,C', 'HARD'),
('Eb', 'SEVENTH_SHARP5', 'Eb7#5', 'Eb,G,B,Db', 'HARD'),
('E', 'SEVENTH_SHARP5', 'E7#5', 'E,G#,B#,D', 'HARD'),
('F', 'SEVENTH_SHARP5', 'F7#5', 'F,A,C#,Eb', 'HARD'),
('F#', 'SEVENTH_SHARP5', 'F#7#5', 'F#,A#,D,E', 'HARD'),
('G', 'SEVENTH_SHARP5', 'G7#5', 'G,B,D#,F', 'HARD'),
('Ab', 'SEVENTH_SHARP5', 'Ab7#5', 'Ab,C,E,Gb', 'HARD'),
('A', 'SEVENTH_SHARP5', 'A7#5', 'A,C#,E#,G', 'HARD'),
('Bb', 'SEVENTH_SHARP5', 'Bb7#5', 'Bb,D,F#,Ab', 'HARD'),
('B', 'SEVENTH_SHARP5', 'B7#5', 'B,D#,G,A', 'HARD'),
-- HARD 추가: 7b5 (12키)
('C', 'SEVENTH_FLAT5', 'C7b5', 'C,E,Gb,Bb', 'HARD'),
('C#', 'SEVENTH_FLAT5', 'C#7b5', 'C#,E#,G,B', 'HARD'),
('D', 'SEVENTH_FLAT5', 'D7b5', 'D,F#,Ab,C', 'HARD'),
('Eb', 'SEVENTH_FLAT5', 'Eb7b5', 'Eb,G,Bbb,Db', 'HARD'),
('E', 'SEVENTH_FLAT5', 'E7b5', 'E,G#,Bb,D', 'HARD'),
('F', 'SEVENTH_FLAT5', 'F7b5', 'F,A,Cb,Eb', 'HARD'),
('F#', 'SEVENTH_FLAT5', 'F#7b5', 'F#,A#,C,E', 'HARD'),
('G', 'SEVENTH_FLAT5', 'G7b5', 'G,B,Db,F', 'HARD'),
('Ab', 'SEVENTH_FLAT5', 'Ab7b5', 'Ab,C,Ebb,Gb', 'HARD'),
('A', 'SEVENTH_FLAT5', 'A7b5', 'A,C#,Eb,G', 'HARD'),
('Bb', 'SEVENTH_FLAT5', 'Bb7b5', 'Bb,D,Fb,Ab', 'HARD'),
('B', 'SEVENTH_FLAT5', 'B7b5', 'B,D#,F,A', 'HARD');
